chore: update JSDoc
KILTprotocol/sdk-js pull request #350
Opened 2021-03-02 09:45 UTC by Diiaablo95

- Update Typedoc dependency to ^0.19
- Adjust some doc errors

## fixes KILTProtocol/ticket#312
I updated the documentation to repair broken links and inconsistencies with the current SDK status. Nevertheless, as we also discussed, I think the documentation still needs a large reworking, as different parts of the SDK have very different documentation styles.

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
- [x] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [x] I have documented the changes (where applicable)

2021-03-03 17:35 UTC, tjwelde commented
While I was looking at this I noticed, that now with the SDK split-up, the structure of the API reference doesn't make much sense anymore.
In the past we have used `typedoc-plugin-external-module-name` to aggregate files in folders into separate modules. But even if we use it again, we might have to clarify what lives in what package.

2021-03-04 09:49 UTC, tjwelde commented
As discussed:
- Remove typedoc related files and commands from all packages
- Make sure the corresponding github workflow uses the command from root
- Exclude lib folder
- Fix paths showing up in documenation
Thanks ☺️

2021-03-05 12:24 UTC, Diiaablo95 commented
Ok I guess I fixed the errors of the CI. @tjwelde or perhaps @rflechtner would you mind taking a look? Thanks!

2021-03-05 13:44 UTC, tjwelde requested changes
Looks very clean again, just small things

2021-03-05 13:44 UTC, tjwelde commented on packages/chain-helpers/src/blockchain/Blockchain.spec.ts
> +/* eslint-disable */
this will disable ALL eslint checks. Is that wanted here?

2021-03-05 13:44 UTC, tjwelde commented on packages/core/src/__integrationtests__/Attestation.spec.ts
> - * @group integration/attestation
We have to add the `@group` tags to the integration tests, so that they are triggered correctly via the `yarn run test:integration:run` command

2021-03-05 16:39 UTC, tjwelde approved these changes
LGTM
![](https://media2.giphy.com/media/3oFyDq6BEAim8LG836/giphy.gif)

2021-03-09 06:33 UTC, merged