chore: bundle sdk-js and publish in /dist
KILTprotocol/sdk-js pull request #367
Opened 2021-04-07 15:01 UTC by LeonFLK

## fixes KILTProtocol/ticket#312

Adds webpack configuration that builds sdk-js bundle in the packages /dist folder as minimized and non-minimized.
Publish with dist folder.

## How to test:
Add to html as script `<script src...`

use @kiltprotocol/sdk-js and it's exposed functionalities.

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [x] I have documented the changes (where applicable)

2021-04-07 16:07 UTC, tjwelde commented
I think it is not completely clear, how to use this new bundle.
I think we should 
a) automatically put it on a CDN, as is specified in the ticket and 
b) think about having another package for the bundled version, or
c) include the minified version in our sdk-js package, but document it in the README

2021-04-08 10:52 UTC, LeonFLK commented
Totally agree, I will create a ticket to update the README, to show case how we can access the npm cdn and use the SPA.

unpkg and npmcdn automatically provide for npm published packages.

Once merged to develop we can access the bundle via  `{npmcdn.com/unpkg.com)/:package@:version/:file`
example: https://npmcdn.com/@kiltprotocol/sdk-js@0.20.0/lib/index.js

The bundles are named : sdk-js.min.umd.js and sdk-js.umd.js, do we want to stick to the sdk-js term?

2021-04-08 15:14 UTC, tjwelde commented
I don't really have a strong opinion in the naming of the bundle

2021-04-09 14:33 UTC, LeonFLK commented
We could name the bundle kilt, that would be my suggestion.

As an integrator I'm sure I'd be glad if the embedded bundles are easily distinguished.

Other than that, is the PR approved?

2021-04-19 12:39 UTC, rflechtner commented
> We could name the bundle kilt, that would be my suggestion.
> 
> As an integrator I'm sure I'd be glad if the embedded bundles are easily distinguished.
> 
> Other than that, is the PR approved?

I imagine it could also add to the confusion, especially if we decide to bundle other packages as well (core?). Maybe sdk-js is best, because then the reference is clear

2021-04-21 13:07 UTC, LeonFLK commented
Okay so for the naming of the files we stick to the implemented name.
As long as we do not release SPA bundles for different packages we want to access the bundle via the window.kilt object.

2021-05-05 15:58 UTC, tjwelde requested changes

2021-05-05 15:58 UTC, tjwelde commented on docs/development-setup.md
> +## Embed bundle in HTML
Development setup is only for people working on the SDK, not _with_.

Please move these instructions into the README.md

2021-05-05 17:11 UTC, tjwelde approved these changes
LGTM

2021-05-05 17:11 UTC, merged