feat: add support for delegation deposit reclaim
KILTprotocol/sdk-js pull request #436
Opened 2021-11-08 16:16 UTC by Diiaablo95

# Add support for delegation deposit reclaim

This PR fixes https://github.com/KILTprotocol/ticket/issues/1685 by adding a new function on `DelegationNode` and the relative chain file to generate a `SubmittableExtrinsic` for the `reclaim_deposit` chain function.

This PR targets `develop` commit https://github.com/KILTprotocol/mashnet-node/commit/fc56483437001e68174f47b424fc0c6b01ad35be and `master` commit https://github.com/KILTprotocol/mashnet-node/commit/dff5ae8646753484cf594cd9af1184bd93bd405e.

Companion PR (already merged) -> https://github.com/KILTprotocol/mashnet-node/pull/295

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [x] I have documented the changes (where applicable)

2021-11-10 13:18 UTC, Dudleyneedham requested changes
Some minor changes

2021-11-10 13:18 UTC, Dudleyneedham commented
The tests are also failing.

2021-11-10 13:27 UTC, Diiaablo95 commented
The issues with tests is because we are mistakenly referring to the `latest-develop` as the latest master release, which does not have delegation deposits yet. @weichweich can we fix that, so that I can re-trigger the pipeline and see if it goes through?

2021-11-10 13:28 UTC, Diiaablo95 commented on packages/core/src/delegation/DelegationNode.ts
> +  private childrenIdentifiers: Array<IDelegationNode['id']> = []
Yes but I had to make `childrenIds` a public getter, while also having a private variables, and they could not be called the same. Plus, using a leading `_` would trigger lint warnings. I did not find any other way to expose what I needed to expose.

2021-12-03 18:45 UTC, tjwelde commented on packages/core/src/delegation/DelegationNode.ts
> +  private childrenIdentifiers: Array<IDelegationNode['id']> = []
Why do they need to be private? (also note, that after transpiling to javascript, it is not private anymore, just a hint for people working with typescript)

2021-12-03 18:47 UTC, tjwelde approved these changes
`childrenIds` could be kept public (just not readonly), otherwise LGTM

2021-12-06 07:35 UTC, Diiaablo95 commented on packages/core/src/delegation/DelegationNode.ts
> +  private childrenIdentifiers: Array<IDelegationNode['id']> = []
Yeah the idea is to follow, where possible, object-oriented encapsulation. Ok that with JS we lose all this nice info, but for TS developers it should not be possible to alter the array of children without revoking them. That is why I did not want to publicly expose it.

2021-12-06 09:18 UTC, Dudleyneedham approved these changes
LGTM

2021-12-06 09:25 UTC, merged